sudo: false

# cache:
#  apt: true

addons:
  apt:
    packages:
    - cmake

branches:
  only: 
    - master
    - CITest

# global:
#   - GIT_TAG=<your version string>
#   - secure: <encrypted_gh_token>
env:
  global:
    - GIT_TAG="librarytest11"
    - secure: "kF66P+xYUADGdu9Yjty7DCeUIQbV10BdaSO5MoiiYy0hgItltPXeJdsqlkyFfcH7y4LWTwPfhdTEE5tCez+BL0yYJn9fqRGm2BDO5xaEDOaIEiwh98KpXAEUuhs5hRnZ5kFVEfI6kdTYwrYKTJQABr2PeBXZWWc51lGyC8aC18PAlFr4LC3d3vRa+e3IeSVyiYoScoZlacGe25UU4PVKI2KIsh6n9RUm6oEk4ptjanqhZjzF7JlbPsFly/3mxmMekQZMjW8KuX5BF+ZiO4KnFZ49pxs+6+68lf2kPtY3KeIZjrRak3mLucgN3bXnrRsAFrW3iXMftF7pFarRLeyupfKtwZMEv7LNGVfg/DivNCqCFKGAU+p1BCJJ3ae1bujMEF0qGSn2yT3ItFsEk0VPDFP5b76eEQpwqOt/R5vNE1+wox+lhJHTJVK1BctS1AT9ygKDKhkQvSCDUBX1OMdymB0KpualW16slj05asLyqPRXXxXtPWY0Wziil+z5B4A7Dk67D5GATrwR4ecINuaAu+PxB3ReqVAhLTGXuEZHEMd45Zv8KeJPcddbsqLvLiHJIYrcUtvOJLp4Iv+ZFFE2BNeoe/P1WGKd1x3w1Mc3nLr3ZQ6UZaSRVPtlZB6CLSxj3QsL74moW0EZ5iUzYzteoYV2aLeeKWsFrfbkzm01qJY="

matrix: 
   include: 
     # - os: linux
     #   language: cpp
     #   compiler: gcc
     #   env: ANDROID_ABIs="arm64-v8a"
     #   env: ANDROID_TARGET_API="23"
     #   env: TOOLCHAIN_NAME="aarch64-linux-android-4.9"
     
     - os: linux
       language: cpp
       compiler: gcc
       env: ANDROID_ABIs="armeabi-v7a"
       env: ANDROID_TARGET_API="23"
       env: TOOLCHAIN_NAME="arm-linux-androideabi-4.9"
     
     - os: linux
       language: cpp
       compiler: gcc
       env: ANDROID_ABIs="x86_64"
       env: ANDROID_TARGET_API="23"
       env: TOOLCHAIN_NAME="x86_64-4.9"
     
     - os: linux
       language: cpp
       compiler: gcc
       env: ANDROID_ABIs="x86"
       env: ANDROID_TARGET_API="23"
       env: TOOLCHAIN_NAME="x86-4.9"
     
     # - os: osx
     #   osx_image: xcode8.3
     #   language: objective-c
     #   compiler: clang

     # - os: osx
     #   osx_image: xcode8.3
     #   language: objective-c
     #   compiler: gcc
     #   env: IOS_SDK_VERSION="iPhoneOS10.3.sdk"
     #   xcode_sdk: iOS 10.3

     # - os: osx
     #   osx_image: xcode9
     #   language: objective-c
     #   compiler: clang

     # - os: osx
     #   osx_image: xcode9
     #   language: objective-c
     #   compiler: gcc
     #   env: IOS_SDK_VERSION="iPhoneOS11.0.sdk"
     #   xcode_sdk: iOS 11.0

# iOS Image Setting : 
# https://blog.travis-ci.com/
# https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-7.3.1
# https://docs.travis-ci.com/user/languages/objective-c
# https://github.com/timsutton/osx-vm-templates
# 
# Android NDK :
# http://dl.google.com/android/repository/android-ndk-r11c-windows-x86.zip
# http://dl.google.com/android/repository/android-ndk-r11c-windows-x86_64.zip
# wget http://dl.google.com/android/ndk/android-ndk-r8c-darwin-x86.tar.bz2
# tar -jxvf android-ndk-r8c-darwin-x86.tar.bz2
# cd android-ndk-r8c
###
# iOS?
# if [ "$CXX" = "clang++" ]; then export CXXFLAGS="-std=c++11 -arch armv7s -isysroot /Applications/Xcode6-Beta6.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk";
# if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7";
# export IOS_PLATFORM_LOCATION="OS";
# export CXXFLAGS="-std=c++11 -arch armv7s -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk";
# if ng
# cmake -DBUILD_ANDROID:BOOL=OFF -DBUILD_IOS_DEVICE:BOOL=ON -BUILD_IOS_SIMULATOR:BOOL=OFF ../;
# Travis CI osx image?
# https://docs.travis-ci.com/user/osx-ci-environment/
# brew update >/dev/null;
# http://hkdnet.hatenablog.com/entry/2016/07/30/215925
#       cd $(brew --repository);
#       git fetch origin;
#       git reset --hard origin/master;
#       brew update;
# cmake -DBUILD_ANDROID:BOOL="OFF" -DBUILD_IOS_DEVICE:BOOL="ON" -BUILD_IOS_SIMULATOR:BOOL="OFF" ../;
# CMake 3.6.2
# wget --no-check-certificate -qO- https://cmake.org/files/v3.6/cmake-3.6.2-Darwin-x86_64.tar.gz -O /tmp/cmake-3.6.2-Darwin-x86_64.tar.gz;
# tar -xvf /tmp/cmake-3.6.2-Darwin-x86_64.tar.gz;
# export PATH=$PWD/cmake-3.6.2-Darwin-x86_64/bin/:$PATH;
# 
###
# 
# export IOS_PLATFORM_LOCATION="OS";
# export CXXFLAGS="-std=c++11 -arch armv7 armv7s arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk";
# 
# xcode-select -print-path;
# old()
# brew tap homebrew/boneyard;
# brew install clang-omp;
# export C_INCLUDE_PATH=/usr/local/Cellar/libiomp/!date!/include/libiomp:$C_INCLUDE_PATH;
# export CPLUS_INCLUDE_PATH=/usr/local/Cellar/libiomp/!date!/include/libiomp:$CPLUS_INCLUDE_PATH;
# export LIBRARY_PATH=/usr/local/Cellar/libiomp/!date!/lib:$LIBRARY_PATH;
# 
# brew install llvm;
# travis-ci use ng alias
# alias clang-omp='/usr/local/opt/llvm/bin/clang -fopenmp -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib';
# alias clang-omp++='/usr/local/opt/llvm/bin/clang++ -fopenmp -L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib';
# Boost Build?
# http://blog.livedoor.jp/tek_nishi/archives/7603570.html
# sudo ln -s /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/include /usr/include/arm
# build Timeout 
# cmake -DBUILD_ANDROID:BOOL="OFF" -DBUILD_IOS_DEVICE:BOOL="ON" -DBUILD_IOS_SIMULATOR:BOOL="ON" ../;
# use?
# brew tap totakke/openni2;
# brew install openni2;
###
# sdk check 8.0
# git clone -b v6.3.0 https://github.com/Kitware/VTK.git;
###
# sdk check contains 9.3(Timeout 50 min ...)
# git clone -b v7.0.0 https://github.com/Kitware/VTK.git;
# cd VTK;
# mkdir build && cd build;
# cmake -DVTK_IOS_BUILD=BOOL="ON" ../;
# travis_wait 60 make -j4 VERBOSE=1 2>&1;
# cd ../..;
# mac on android?
# start
# wget http://dl.google.com/android/android-sdk_r24.0.2-linux.tgz;
# tar zxvf android-sdk_r24.0.2-linux.tgz;
# sudo mv android-sdk-linux/ /opt/;
# rm android-sdk_r24.0.2-linux.tgz;
# export ANDROID_HOME=/opt/android-sdk-linux;
# export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools;
# 
# wget https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip;
# unzip -q android-ndk-r14b-linux-x86_64.zip;
# sudo mv android-ndk-r14b /opt/;
# rm android-ndk-r14b-linux-x86_64.zip;
# export ANDROID_NDK_HOME=/opt/android-ndk-r14b;
# export PATH=${PATH}:$ANDROID_NDK_HOME;
# 
# git clone -b v7.0.0 https://github.com/Kitware/VTK.git;
# cd VTK;
# mkdir build && cd build;
# cmake -DVTK_IOS_BUILD="ON" ../;
# travis_wait 60 make -j4 VERBOSE=1 2>&1;
# cd ../..;
# Android
# cmake -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=${ANDROID_NDK}/prebuilt/linux-x86_64/bin/make.exe -DANDROID_NATIVE_API_LEVEL=${ANDROID_TARGET_API} -DANDROID_ABI=${ANDROID_ABIs} -DANDROID_TOOLCHAIN=${compiler} ..
# ios(macosx only)
# cmake -DBUILD_ANDROID:BOOL="OFF" -DBUILD_IOS_DEVICE:BOOL="ON" -DBUILD_IOS_SIMULATOR:BOOL="ON" ../;
# Xcode 9.0
# iphoneos11.0
# set(CMAKE_IOS_SDK_ROOT /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk)
# Xcode 8.3
# iphoneos10.3
# set(CMAKE_IOS_SDK_ROOT /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk)
###
before_install:
  - if [[ $TRAVIS_OS_NAME = "osx" ]]; then
      brew prune;
      brew update >/dev/null;
      brew install llvm;
      
      brew tap totakke/openni2;
      brew install openni2;
      
      mkdir build && cd build;
      cmake -DBUILD_ANDROID:BOOL="OFF" -DBUILD_IOS_DEVICE:BOOL="ON" -DBUILD_IOS_SIMULATOR:BOOL="ON" -DCMAKE_IOS_SDK_ROOT:FILEPATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/$IOS_SDK_VERSION" ../;
    fi

  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      wget --no-check-certificate -qO- http://www.cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz -O /tmp/cmake-3.6.2-Linux-x86_64.tar.gz;
      tar -xf /tmp/cmake-3.6.2-Linux-x86_64.tar.gz;
      export PATH=$PWD/cmake-3.6.2-Linux-x86_64/bin/:$PATH;
      
      wget -qO- http://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip -O /tmp/android-ndk-r14b-linux-x86_64.zip;
      unzip -q /tmp/android-ndk-r14b-linux-x86_64.zip;
      cd android-ndk-r14b;
      export ANDROID_NDK=$PWD;
      cd ..;
      
      export PATH=$ANDROID_NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:$PATH;
      
      - dd if=/dev/zero of=/swapfile bs=1024 count=4194304;
      - mkswap /swapfile;
      - swapon /swapfile;
      
      mkdir build;
      cd build;
      cmake -DBUILD_ANDROID:BOOL="ON" -DBUILD_IOS_DEVICE:BOOL="OFF" -DBUILD_IOS_SIMULATOR:BOOL="OFF" -DCMAKE_TOOLCHAIN_FILE:FILEPATH=${ANDROID_NDK}/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=${ANDROID_NDK}/prebuilt/linux-x86_64/bin/make.exe -DANDROID_TOOLCHAIN_NAME=${TOOLCHAIN_NAME} -DANDROID_NATIVE_API_LEVEL=${ANDROID_TARGET_API} -DANDROID_ABI=${ANDROID_ABIs} -DANDROID_TOOLCHAIN=${compiler} ..;
    fi

# install:
#   - travis_wait 60 make -j4 VERBOSE=1 2>&1
# - ls
# http://www.vtk.org/Wiki/VES/Point_Cloud_Library
# - open build/HelloPCL.xcodeproj
# xcodebuild
# http://blog.ch3cooh.jp/entry/20150210/1423573065
# - xcodebuild -project build/HelloPCL.xcodeproj -target HelloPCL -sdk iphoneos -configuration Release build
# ves install(no use reason : old module)
# git clone git://vtk.org/VES.git
# iOS Sample
# git clone -b pcl-ios-app git://vtk.org/stage/VES.git
# http://www.vtk.org/Wiki/VES/Developers_Guide#iOS_instructions
# - mkdir build
# - cd build
# - cmake -DVES_IOS_SUPERBUILD=1 ../
# - travis_wait 60 make -j4 VERBOSE=1 2>&1
# - ln -s /Users/travis/build/Sirokujira/pcl-superbuild/build/CMakeExternals/Install/frameworks ./frameworks
# - cd ..
# - cd ../apps/ios/HelloPCL
# - bash cmake_command.sh
# - cd ../../../build
# xcode open
# - open build/HelloPCL.xcodeproj
# xcode command line build
# http://blog.ch3cooh.jp/entry/20150210/1423573065
# simulation build
# - xcodebuild -project build/HelloPCL2.xcodeproj -target HelloPCL2 -sdk iphonesimulator -configuration Debug build
# - xcodebuild -project build/HelloPCL2.xcodeproj -target HelloPCL2 -sdk iphoneos -configuration Release build
# before vtk build module copy?
# - bash cmake_command.sh
# TestCode
# - cd ../apps/ios/HelloPCL2
# - xcodebuild -project build/HelloPCL2.xcodeproj -target HelloPCL2 -sdk iphoneos -configuration Release build
# - cd ../../../build
# warning
# 4MB maximum log size a little low
# https://www.google.co.jp/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwiEhOiJyN_UAhXHgrwKHV2BCL8QFggiMAA&url=https%3A%2F%2Fgithub.com%2Ftravis-ci%2Ftravis-ci%2Fissues%2F1382&usg=AFQjCNHunsY-8__7zqF6zQwurd-CKnqq6w&cad=rja
# - travis_wait 60 make -j4 VERBOSE=1 2>&1
# add swapfile
# dd if=/dev/zero of=/swapfile bs=1024 count=4194304
# mkswap /swapfile
# swapon /swapfile
script:
    - travis_wait 60 make -j4 VERBOSE=1 2>&1

# after_success:
#     - zip -r pcl-releases-$TRAVIS_OS_NAME-$GIT_TAG.zip ./CMakeExternals/Install

# after_failure:
#     - cat ./CMakeExternals/Build/pcl-ios-device/CMakeFiles/CMakeOutput.log
#     - cat ./CMakeExternals/Build/pcl-ios-device/CMakeFiles/CMakeError.log
#     - cat ./CMakeExternals/Build/pcl-ios-simulator/CMakeFiles/CMakeOutput.log
#     - cat ./CMakeExternals/Build/pcl-ios-simulator/CMakeFiles/CMakeError.log
# 
# - zip -q packages/pcl-rleases-$GIT_TAG.zip -r ./CMakeExternals/Install
# before_deploy:
#     - mkdir packages
#     - tar czf packages/pcl-releases-$TRAVIS_XCODE_SDK-$GIT_TAG.tar.gz ./CMakeExternals/Install
#     - zip -q packages/pcl-releases-$TRAVIS_XCODE_SDK-$GIT_TAG.zip -r ./CMakeExternals/Install
#     - zip -q packages/pcl-releases-frameworks-$TRAVIS_XCODE_SDK-$GIT_TAG.zip -r ./CMakeExternals/Install/frameworks
#     - git config --global user.name "Sirokujira"
#     - git config --global user.email "toru753@gmail.com"
#     - git tag $GIT_TAG -a -m "Commit from Travis CI for build $TRAVIS_BUILD_NUMBER"
#     - git push --quiet https://$GH_TOKEN@github.com/Sirokujira/pcl-superbuild.git --tags 2> /dev/null
# 
# 
# deploy:
#   provider: releases
#   skip_cleanup: true
#   api_key: 
#     secure: "nVLOBizFgvnJvKssHPJfeN5AtQKrdZE/EDHtr1UC5PJNqZNdCAr8DcQS0hj6bRZ3iYfb+qn4OZV/HOfG/GY46N4CoFuNaOVFqajSZsheF01zvHob3/7bK7EXCybk8QzUIDAV77JjZiQacXJtX0asHPDAgJBScxU1KEC4osaxRy2p3ebw5JURFQArpt8vvK0180ZkH6E0A6qrsBBvaXUPTQ7gM0t/sDhSrPunu0zjKeHPe8VeUp/ELx4fohdiQGSRzf7X7Jmph3dXNSgJb4UBULWvBoQnmUlRCMfqPOkpsbEWWo/ZaaWb0N48GH0RtSIHX+Oampu8SFRvcQVNBSZMPbw+CTaA0Ij1mMhRQgqgjEroiX3y1WOxcT7eiZtwDToUQnm2CqbiTszm5d/bWY4Z3ln4CyiFLUDjTrjD/z4FJi6sgRNMOybo4tAYixuhI4f4wdRRwYOdM9a919LEgM8XltxO+H0KgqDeVjOdmLinxQ9XefZs3k6uRQuEfDIkoyRopt7wKmbhzgs9tOZuEVySxJAFOU17iPvn/BrjU9/g+MRRbnxuajPSPia7/09uHZ7IJJSMK35qvlBjohnVbY6ZHKjTFw3QjOrH7DYATAHvr9XyKlmKIzeubVRzeK9k932WweCa1ySro+kpoJVxwxDs6XnyPe/nnjkt4FovGJNIJLA="
#   file:
#     - packages/pcl-releases-$TRAVIS_XCODE_SDK-$GIT_TAG.tar.gz
#     - packages/pcl-releases-$TRAVIS_XCODE_SDK-$GIT_TAG.zip
#     - packages/pcl-releases-frameworks-$TRAVIS_XCODE_SDK-$GIT_TAG.zip
#   on:
#     tags: false
#     branch: master

