language: cpp 


matrix: 
   include: 
     - os: linux
       compiler: gcc
     - os: osx
       compiler: clang++

addons: 
   apt: 
    sources: 
      - kalakris-cmake 
      - boost-latest 
      - kubuntu-backports 
    packages: 
      - cmake 
      - libgtest-dev 
      - doxygen-latex 
      - libusb-1.0-0-dev 

cache: 
  directories: 
  - $HOME/flann 
  - $HOME/vtk 
  - $HOME/qhull 
  - $HOME/doxygen 

# http://dl.google.com/android/repository/android-ndk-r11c-windows-x86.zip
# http://dl.google.com/android/repository/android-ndk-r11c-windows-x86_64.zip
# wget http://dl.google.com/android/ndk/android-ndk-r8c-darwin-x86.tar.bz2
# tar -jxvf android-ndk-r8c-darwin-x86.tar.bz2
# cd android-ndk-r8c
before_install:
  - if [[ $TRAVIS_OS_NAME = "osx" ]]; then
      brew update >/dev/null;
      wget http://dl.google.com/android/repository/android-ndk-r11c-darwin-x86_64.zip;
      unzip -q android-ndk-r11c-darwin-x86_64.zip;
      cd android-ndk-r11c;
      export ANDROID_NDK=$PWD;

      cd ..;
      mkdir build;
      cd build;
      cmake -DBUILD_IOS_DEVICE:BOOL=ON -BUILD_IOS_SIMULATOR:BOOL=ON ../;
    fi

  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      wget http://dl.google.com/android/repository/android-ndk-r11c-linux-x86_64.zip;
      unzip -q android-ndk-r11c-linux-x86_64.zip;
      cd android-ndk-r11c;
      export ANDROID_NDK=$PWD;

      cd ..;
      mkdir build;
      cd build;
      cmake ../;
    fi


install:
    - travis_wait 40 make

