sudo: false 
language: cpp 
compiler: 
  - gcc
  - clang

matrix: 
   include: 
     - os: linux
       language: cpp
       compiler: gcc
     - os: osx
       language: cpp
       compiler: clang
 addons: 
  apt: 
    sources: 
      - kalakris-cmake 
      - boost-latest 
      - kubuntu-backports 
    packages: 
      - cmake 
      - libgtest-dev 
      - doxygen-latex 
      - libusb-1.0-0-dev 
cache: 
  directories: 
  - $HOME/flann 
  - $HOME/vtk 
  - $HOME/qhull 
  - $HOME/doxygen 


before_install:
  - if [[ $TRAVIS_OS_NAME = "osx" ]]; then
      brew update >/dev/null;
      wget http://dl.google.com/android/ndk/android-ndk-r8c-darwin-x86.tar.bz2
      tar -jxvf android-ndk-r8c-darwin-x86.tar.bz2
      cd android-ndk-r8c
      export ANDROID_NDK=$PWD
      cd ..
      mkdir build
      cd build
      cmake -DBUILD_IOS_DEVICE:BOOL=ON -BUILD_IOS_SIMULATOR:BOOL=ON ../
    fi

  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      wget http://dl.google.com/android/ndk/android-ndk-r11c-linux-x86_64.tar.bz2
      tar -jxvf android-ndk-r11c-linux-x86_64.tar.bz2
      cd android-ndk-r11c
      export ANDROID_NDK=$PWD
      cd ..
      mkdir build
      cd build
      cmake ../
    fi

    # - bash .travis.sh install

install:
    # travis_wait 40 make;
    travis_wait 40 make -j2;

    # - bash .travis.sh install TASK
