version: 1.0.{build}

image: Visual Studio 2015

# Appveyor Build environment 
# https://www.appveyor.com/docs/build-environment/
environment:
    matrix:
    # 32 bit
      MinGW_ROOT: "C:\\MinGW"
      MinGW: "C:\\MinGW\\bin"
      MSYS_ROOT: "C:\\MinGW\\msys\\1.0"
      # CC="%MINGW%\\gcc"
      # CXX="%MINGW%\g++"

    # 64 bit?
    # - MinGW_ROOT: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1"
    #   MinGW: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\bin"
    #   MSYS_ROOT: "C:\\msys64"

# CMake building for MinGW issue with Git sh.exe 
# http://help.appveyor.com/discussions/problems/3193-cmake-building-for-mingw-issue-with-git-shexe
install:
- cmd: >-
    set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
    
    mkdir build
    
    cd build
    
    cmake -G "MinGW Makefiles" -DBUILD_ANDROID:BOOL="ON" -DBUILD_IOS_DEVICE:BOOL="OFF" -DBUILD_IOS_SIMULATOR:BOOL="OFF" ../

build_script:
- cmd: >-
    mingw32-make
    
    zip -q pcl-superbuild.zip -r ./CMakeExternals/Install

artifacts:
- path: build\pcl-superbuild.zip
  name: Release

