version: 1.0.{build}

image: Visual Studio 2015

cache:
- cachebuild

# mingw + windows
# https://hcteq.wordpress.com/2014/07/14/compiling-pcl-for-android-in-windows-cmake-gui/
# Compiling PCL for android(windows)
# https://www.appveyor.com/docs/build-environment/
environment:
    matrix:
    # 32 bit
    - MinGW_ROOT: "C:\\MinGW"
      MinGW: "C:\\MinGW\\bin"
      MSYS_ROOT: "C:\\MinGW\\msys\\1.0"
      # CC="%MINGW%\\gcc"
      # CXX="%MINGW%\g++"
      ROOT: "C:\\projects"
      ANDROID_NDK: "C:\\projects\\android-ndk-r10e"
      NDK_VERSION: "r10e"
      OS_ARCH: "32"

    # 64 bit?
    # - MinGW_ROOT: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1"
    #   MinGW: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\bin"
    #   MSYS_ROOT: "C:\\msys64"
    #   ANDROID_NDK: "C:\\projects\\android-ndk-r10e"
    #   NDK_VERSION: "r10e"
    #   OS_ARCH: "64"

# - ps: Import-Module ".\appveyor\PS-Zip\PS-Zip.psm1" -Force
# - ps: .\appveyor\install.ps1
install:
    - ps: Start-FileDownload "https://dl.google.com/android/repository/android-ndk-r10e-windows-x86.zip"
    - ps: Expand-Archive -Path android-ndk-r10e-windows-x86.zip -DestinationPath "C:\\projects"


# CMake building for MinGW issue with Git sh.exe 
# http://help.appveyor.com/discussions/problems/3193-cmake-building-for-mingw-issue-with-git-shexe
# https://github.com/jibsen/brieflz/blob/0c6fb73984f11e697dfaade5cdc5e291c1655c67/appveyor.yml
# 32bit?
# set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
# long path(boost)
# https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows
# git config --system core.longpaths true
# - mkdir build
# - cd build
before_build:
    - git config --system core.longpaths true
    - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
    - set PATH=%MinGW%;%PATH%
    - copy "C:\MinGW\bin\mingw32-make.exe" "C:\MinGW\bin\make.exe"
    - cd cachebuild
    - cmake -G "MinGW Makefiles" -DBUILD_ANDROID:BOOL="ON" -DBUILD_IOS_DEVICE:BOOL="OFF" -DBUILD_IOS_SIMULATOR:BOOL="OFF" ../

build_script:
- cmd: >-
    make -j4
    
    7z a pcl-superbuild.zip -r ./CMakeExternals/Install/*.*

artifacts:
- path: cachebuild\pcl-superbuild.zip
  name: Release

