version: 1.0.{build}

image: Visual Studio 2015

cache:
- cachebuild

# mingw + windows
# https://hcteq.wordpress.com/2014/07/14/compiling-pcl-for-android-in-windows-cmake-gui/
# Compiling PCL for android(windows)
# https://www.appveyor.com/docs/build-environment/
# -DCMAKE_C_COMPILER="C:/projects/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc.exe"
# -DCMAKE_CXX_COMPILER="C:/projects/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++.exe"
# Toolchain
# https://developer.android.com/ndk/guides/standalone_toolchain.html
environment:
    matrix:
    # "arm64-v8a"
    # - MinGW_ROOT: "C:\\MinGW"
    # - MinGW_ROOT: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1"
    #   MinGW: "C:\\MinGW\\bin"
    #   MSYS_ROOT: "C:\\MinGW\\msys\\1.0"
    #   # CC: "C:/projects/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc-4.9.exe"
    #   # CXX: "C:/projects/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++.exe"
    #   ANDROID_NDK: "C:/projects/android-ndk-r14b"
    #   OS_ARCH: "64"
    #   CMAKE_COMMAND: "C:\\Program Files (x86)\\cmake\\bin"
    #   ANDROID_ABIs: "arm64-v8a"
    #   ANDROID_TARGET_API: "23"
    #   TOOLCHAIN_NAME: "aarch64-linux-android-4.9"

    # armeabi-v7a
    - MinGW_ROOT: "C:\\MinGW"
      MinGW: "C:\\MinGW\\bin"
      MSYS_ROOT: "C:\\MinGW\\msys\\1.0"
      # CC: "C:/projects/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc-4.9.exe"
      # CXX: "C:/projects/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++.exe"
      ANDROID_NDK: "C:/projects/android-ndk-r14b"
      OS_ARCH: "64"
      CMAKE_COMMAND: "C:\\Program Files (x86)\\cmake\\bin"
      ANDROID_ABIs: "armeabi-v7a"
      ANDROID_TARGET_API: "23"
      TOOLCHAIN_NAME: "arm-linux-androideabi-4.9"

    # (mips64)(simulation?)
    # - MinGW_ROOT: "C:\\MinGW"
    # - MinGW_ROOT: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1"
    #   MinGW: "C:\\MinGW\\bin"
    #   MSYS_ROOT: "C:\\MinGW\\msys\\1.0"
    #   # CC: "C:/projects/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc-4.9.exe"
    #   # CXX: "C:/projects/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++.exe"
    #   ANDROID_NDK: "C:\\projects\\android-ndk-r14b"
    #   OS_ARCH: "64"
    #   CMAKE_COMMAND: "C:\\Program Files (x86)\\cmake\\bin"
    #   ANDROID_ABIs: "mips64"
    #   ANDROID_TARGET_API: "23"
    #   TOOLCHAIN_NAME: "mips64el-linux-android-4.9"

    # (x86_64)(simulation?)
    # - MinGW_ROOT: "C:\\MinGW"
    - MinGW_ROOT: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1"
      MinGW: "C:\\MinGW\\bin"
      MSYS_ROOT: "C:\\MinGW\\msys\\1.0"
      # CC="%MINGW%\\gcc"
      # CXX="%MINGW%\g++"
      ANDROID_NDK: "C:\\projects\\android-ndk-r14b"
      OS_ARCH: "64"
      CMAKE_COMMAND: "C:\\Program Files (x86)\\cmake\\bin"
      ANDROID_ABIs: "x86_64"
      ANDROID_TARGET_API: "23"
      TOOLCHAIN_NAME: "x86_64-4.9"

    # (x86)(simulation?)
    - MinGW_ROOT: "C:\\MinGW"
      MinGW: "C:\\MinGW\\bin"
      MSYS_ROOT: "C:\\MinGW\\msys\\1.0"
      # CC="%MINGW%\\gcc"
      # CXX="%MINGW%\g++"
      ANDROID_NDK: "C:\\projects\\android-ndk-r14b"
      OS_ARCH: "64"
      CMAKE_COMMAND: "C:\\Program Files (x86)\\cmake\\bin"
      ANDROID_ABIs: "x86"
      ANDROID_TARGET_API: "23"
      TOOLCHAIN_NAME: "x86-4.9"

    # 64 bit?
    # - MinGW_ROOT: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1"
    #   MinGW: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\bin"
    #   MSYS_ROOT: "C:\\msys64"
    #   ANDROID_NDK: "C:\\projects\\android-ndk-r14b"
    #   OS_ARCH: "64"
    #   CMAKE_COMMAND: "C:\\Program Files (x86)\\cmake\\bin"

# https://github.com/boostorg/hana/blob/master/.appveyor.yml
# - ps: Import-Module ".\appveyor\PS-Zip\PS-Zip.psm1" -Force
# - ps: .\appveyor\install.ps1
# ############################################################################
# # All external dependencies are installed in C:\projects\deps
# ############################################################################
# - mkdir C:\projects\deps
#
# ############################################################################
# # Install Ninja
# ############################################################################
# - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip"
# - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
# - 7z x ninja.zip -oC:\projects\deps\ninja > nul
# - set PATH=C:\projects\deps\ninja;%PATH%
# - ninja --version
install:
    - ps: Start-FileDownload "https://dl.google.com/android/repository/android-ndk-r14b-windows-x86_64.zip"
    - ps: Expand-Archive -Path android-ndk-r14b-windows-x86_64.zip -DestinationPath "C:\\projects"


# CMake building for MinGW issue with Git sh.exe 
# http://help.appveyor.com/discussions/problems/3193-cmake-building-for-mingw-issue-with-git-shexe
# https://github.com/jibsen/brieflz/blob/0c6fb73984f11e697dfaade5cdc5e291c1655c67/appveyor.yml
# 32bit?
# set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
# long path(boost)
# https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows
# git config --system core.longpaths true
# - mkdir build
# - cd build
# - cmake -G "MinGW Makefiles" -DBUILD_ANDROID:BOOL="ON" -DBUILD_IOS_DEVICE:BOOL="OFF" -DBUILD_IOS_SIMULATOR:BOOL="OFF" ../
# r14 under?
#  -DCMAKE_MAKE_PROGRAM="%ANDROID_NDK%\prebuilt\windows\bin\make.exe"
# r15? over?
#  -DCMAKE_MAKE_PROGRAM="%ANDROID_NDK%\prebuilt\windows-x86_64\bin\make.exe"
# C:\Users\v050493\AppData\Local\Android\Sdk\ndk-bundle\build\cmake
# - cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE="%ANDROID_NDK%\build\cmake\android.toolchain.cmake" -DCMAKE_MAKE_PROGRAM="%ANDROID_NDK%\prebuilt\windows\bin\make.exe" -DANDROID_ABI="%ANDROID_ABIs%" ..
# MinGW
# - set PATH=%MinGW%;%PATH%
# - copy "C:\MinGW\bin\mingw32-make.exe" "C:\MinGW\bin\make.exe"
# use Android_NDK make.exe
# -DCMAKE_C_COMPILER="C:/projects/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc-4.9.exe"
# -DCMAKE_CXX_COMPILER="C:/projects/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++.exe"
# - CC="arm-linux-androideabi-gcc" CXX="arm-linux-androideabi-g++.exe" cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE="%ANDROID_NDK%/build/cmake/android.toolchain.cmake" -DCMAKE_MAKE_PROGRAM="%ANDROID_NDK%/prebuilt/windows-x86_64/bin/make.exe" -DANDROID_ABI="%ANDROID_ABIs%" -DCMAKE_C_COMPILER="arm-linux-androideabi-gcc-4.9.exe" -DCMAKE_CXX_COMPILER="arm-linux-androideabi-g++.exe" -DBUILD_ANDROID:BOOL="ON" -DBUILD_IOS_DEVICE:BOOL="OFF" -DBUILD_IOS_SIMULATOR:BOOL="OFF" ../
# - set PATH=%PATH:C:\Program Files (x86)\cmake\bin;=%
# command 
# - C:\\projects\\tools\\android list sdk -a
# - cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE=%ANDROID_NDK%/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=%ANDROID_NDK%/prebuilt/windows-x86_64/bin/make.exe -DANDROID_TOOLCHAIN_NAME=%TOOLCHAIN_NAME% -DANDROID_NATIVE_API_LEVEL=%ANDROID_TARGET_API% -DANDROID_ABI=%ANDROID_ABIs% -DANDROID_TOOLCHAIN=gcc -DBUILD_ANDROID:BOOL="ON" -DBUILD_IOS_DEVICE:BOOL="OFF" -DBUILD_IOS_SIMULATOR:BOOL="OFF" ../
# - cmake -G "MinGW Makefiles" -DCMAKE_ANDROID_NDK=%ANDROID_NDK% -DCMAKE_TOOLCHAIN_FILE:FILEPATH=%ANDROID_NDK%/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM:FILEPATH=%ANDROID_NDK%/prebuilt/windows-x86_64/bin/make.exe -DANDROID_TOOLCHAIN_NAME=%TOOLCHAIN_NAME% -DANDROID_NATIVE_API_LEVEL=%ANDROID_TARGET_API% -DANDROID_ABI=%ANDROID_ABIs% -DANDROID_TOOLCHAIN=gcc -DBUILD_ANDROID:BOOL="ON" -DBUILD_IOS_DEVICE:BOOL="OFF" -DBUILD_IOS_SIMULATOR:BOOL="OFF" ..
# - cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=%ANDROID_NDK%/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=%ANDROID_NDK%/prebuilt/windows-x86_64/bin/make.exe -DANDROID_TOOLCHAIN_NAME=%TOOLCHAIN_NAME% -DANDROID_NATIVE_API_LEVEL=%ANDROID_TARGET_API% -DANDROID_ABI=%ANDROID_ABIs% -DANDROID_TOOLCHAIN=gcc -DBUILD_ANDROID:BOOL="ON" -DBUILD_IOS_DEVICE:BOOL="OFF" -DBUILD_IOS_SIMULATOR:BOOL="OFF" ../
# https://cmake.org/cmake/help/v3.7/manual/cmake-toolchains.7.html#cross-compiling-for-android
# - cmake -G "Ninja" -DCMAKE_SYSTEM_NAME="Android" -DCMAKE_ANDROID_NDK=%ANDROID_NDK% -DCMAKE_TOOLCHAIN_FILE:FILEPATH=%ANDROID_NDK%/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM:FILEPATH=%ANDROID_NDK%/prebuilt/windows-x86_64/bin/make.exe -DANDROID_TOOLCHAIN_NAME=%TOOLCHAIN_NAME% -DANDROID_NATIVE_API_LEVEL=%ANDROID_TARGET_API% -DANDROID_ABI=%ANDROID_ABIs% -DANDROID_TOOLCHAIN=gcc ../
# no set?
# - set PATH=%ANDROID_NDK%/toolchains/%TOOLCHAIN_NAME%/prebuilt/windows-x86_64/bin;%PATH%
# need?
# - copy "C:\MinGW\bin\mingw32-make.exe" "C:\MinGW\bin\make.exe"
# - cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE:FILEPATH=%ANDROID_NDK%/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM:FILEPATH=%ANDROID_NDK%/prebuilt/windows-x86_64/bin/make.exe -DANDROID_TOOLCHAIN_NAME=%TOOLCHAIN_NAME% -DANDROID_NATIVE_API_LEVEL=%ANDROID_TARGET_API% -DANDROID_ABI=%ANDROID_ABIs% -DANDROID_TOOLCHAIN=gcc -DBUILD_ANDROID:BOOL="ON" -DBUILD_IOS_DEVICE:BOOL="OFF" -DBUILD_IOS_SIMULATOR:BOOL="OFF" ../
# s link
# - mklink /D %ANDROID_NDK%/prebuilt/windows-x86_64/bin/make.exe %MINGW%\bin\make.exe
before_build:
    - git config --system core.longpaths true
    - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
    - set PATH=%MINGW%;%PATH%
    - set PATH=%ANDROID_NDK%/toolchains/%TOOLCHAIN_NAME%/prebuilt/windows-x86_64/bin;%PATH%
    - wmic pagefileset where NAME="C:\\pagefile.sys" set INITIALSIZE=2048, MAXIMUMSIZE=8192
    - cd cachebuild
    - cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE:FILEPATH=%ANDROID_NDK%/build/cmake/android.toolchain.cmake -DANDROID_TOOLCHAIN_NAME=%TOOLCHAIN_NAME% -DANDROID_NATIVE_API_LEVEL=%ANDROID_TARGET_API% -DANDROID_ABI=%ANDROID_ABIs% -DANDROID_TOOLCHAIN=gcc -DBUILD_ANDROID:BOOL="ON" -DBUILD_IOS_DEVICE:BOOL="OFF" -DBUILD_IOS_SIMULATOR:BOOL="OFF" ../

# make -j4
# cmake.exe --build .
# cmake.exe --build . -- -j4
# NG
# Eigen files no ext
# 7z a pcl-superbuild-%ANDROID_ABIs%.zip -r ./CMakeExternals/Install/*.*
build_script:
- cmd: >-
    make -j4
    
    7z a pcl-superbuild-%ANDROID_ABIs%.zip -r ./CMakeExternals/Install/*

# on successful build
# on_success:
#  - 7z a pcl-superbuild-%ANDROID_ABIs%.zip -r ./CMakeExternals/Install/*

# on build failure
# on_failure:
#   - 7z a pcl-superbuild-%ANDROID_ABIs%.zip -r ./CMakeExternals/Install/*

artifacts:
- path: cachebuild\pcl-superbuild-%ANDROID_ABIs%.zip
  name: Release

