version: 1.0.{build}

image: Visual Studio 2015

cache:
- cachebuild

# mingw + windows
# https://hcteq.wordpress.com/2014/07/14/compiling-pcl-for-android-in-windows-cmake-gui/
# Compiling PCL for android(windows)
# https://www.appveyor.com/docs/build-environment/
environment:
    matrix:
    # arm64-v8a
    - MinGW_ROOT: "C:\\MinGW"
      MinGW: "C:\\MinGW\\bin"
      MSYS_ROOT: "C:\\MinGW\\msys\\1.0"
      # CC="%MINGW%\\gcc"
      # CXX="%MINGW%\g++"
      ROOT: "C:\\projects"
      ANDROID_NDK: "C:\\projects\\android-ndk-r14b"
      NDK_VERSION: "r14b"
      OS_ARCH: "32"
      CMAKE_COMMAND: "C:\\Program Files (x86)\\cmake\\bin"
      ANDROID_ABIs: "arm64-v8a"

    # (mips64)(simulation?)
    - MinGW_ROOT: "C:\\MinGW"
      MinGW: "C:\\MinGW\\bin"
      MSYS_ROOT: "C:\\MinGW\\msys\\1.0"
      # CC="%MINGW%\\gcc"
      # CXX="%MINGW%\g++"
      ROOT: "C:\\projects"
      ANDROID_NDK: "C:\\projects\\android-ndk-r14b"
      NDK_VERSION: "r14b"
      OS_ARCH: "32"
      CMAKE_COMMAND: "C:\\Program Files (x86)\\cmake\\bin"
      ANDROID_ABIs: "mips64"

    # (x86_64)(simulation?)
    - MinGW_ROOT: "C:\\MinGW"
      MinGW: "C:\\MinGW\\bin"
      MSYS_ROOT: "C:\\MinGW\\msys\\1.0"
      # CC="%MINGW%\\gcc"
      # CXX="%MINGW%\g++"
      ROOT: "C:\\projects"
      ANDROID_NDK: "C:\\projects\\android-ndk-r14b"
      NDK_VERSION: "r14b"
      OS_ARCH: "32"
      CMAKE_COMMAND: "C:\\Program Files (x86)\\cmake\\bin"
      ANDROID_ABIs: "x86_64"

    # (x86)(simulation?)
    - MinGW_ROOT: "C:\\MinGW"
      MinGW: "C:\\MinGW\\bin"
      MSYS_ROOT: "C:\\MinGW\\msys\\1.0"
      # CC="%MINGW%\\gcc"
      # CXX="%MINGW%\g++"
      ROOT: "C:\\projects"
      ANDROID_NDK: "C:\\projects\\android-ndk-r14b"
      NDK_VERSION: "r14b"
      OS_ARCH: "32"
      CMAKE_COMMAND: "C:\\Program Files (x86)\\cmake\\bin"
      ANDROID_ABIs: "x86"

    # 64 bit?
    # - MinGW_ROOT: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1"
    #   MinGW: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\bin"
    #   MSYS_ROOT: "C:\\msys64"
    #   ANDROID_NDK: "C:\\projects\\android-ndk-r14b"
    #   NDK_VERSION: "r14b"
    #   OS_ARCH: "64"
    #   CMAKE_COMMAND: "C:\\Program Files (x86)\\cmake\\bin"

# - ps: Import-Module ".\appveyor\PS-Zip\PS-Zip.psm1" -Force
# - ps: .\appveyor\install.ps1
install:
    - ps: Start-FileDownload "https://dl.google.com/android/repository/android-ndk-r14b-windows-x86.zip"
    - ps: Expand-Archive -Path android-ndk-r14b-windows-x86.zip -DestinationPath "C:\\projects"


# CMake building for MinGW issue with Git sh.exe 
# http://help.appveyor.com/discussions/problems/3193-cmake-building-for-mingw-issue-with-git-shexe
# https://github.com/jibsen/brieflz/blob/0c6fb73984f11e697dfaade5cdc5e291c1655c67/appveyor.yml
# 32bit?
# set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
# long path(boost)
# https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows
# git config --system core.longpaths true
# - mkdir build
# - cd build
# - cmake -G "MinGW Makefiles" -DBUILD_ANDROID:BOOL="ON" -DBUILD_IOS_DEVICE:BOOL="OFF" -DBUILD_IOS_SIMULATOR:BOOL="OFF" ../
# r14 under?
#  -DCMAKE_MAKE_PROGRAM="%ANDROID_NDK%\prebuilt\windows\bin\make.exe"
# r15? over?
#  -DCMAKE_MAKE_PROGRAM="%ANDROID_NDK%\prebuilt\windows-x86_64\bin\make.exe"
# C:\Users\v050493\AppData\Local\Android\Sdk\ndk-bundle\build\cmake
# - cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE="%ANDROID_NDK%\build\cmake\android.toolchain.cmake" -DCMAKE_MAKE_PROGRAM="%ANDROID_NDK%\prebuilt\windows\bin\make.exe" -DANDROID_ABI="%ANDROID_ABIs%" ..
before_build:
    - git config --system core.longpaths true
    - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
    - set PATH=%MinGW%;%PATH%
    - copy "C:\MinGW\bin\mingw32-make.exe" "C:\MinGW\bin\make.exe"
    - cd cachebuild
    - cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE="%ANDROID_NDK%\build\cmake\android.toolchain.cmake" -DCMAKE_MAKE_PROGRAM="%ANDROID_NDK%\prebuilt\windows\bin\make.exe" -DANDROID_ABI="%ANDROID_ABIs%" ..

# make -j4
# cmake.exe --build .
# cmake.exe --build . -- -j4
build_script:
- cmd: >-
    cmake.exe --build . -- -j4
    
    7z a pcl-superbuild.zip -r ./CMakeExternals/Install/*.*

artifacts:
- path: cachebuild\pcl-superbuild.zip
  name: Release

